# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61316d50c043f1ee7c1607edefca365d0ab179fa973a434e1c0ad368c194b2b53cd7bdb2b0378aeeda5b610be2956fd253d32dbeb401905276484d86a6f8108e

test:
  secret_key_base: 0076b9975e463bdf9fed4fd5c059d38fc8c43709929aa8743973eaf36584a2223b0f72aabdd75afd2880d2ee77c14b903b5e319601aa78892a3b6d628bdc4f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
